#!/bin/sh

PYTHON=python2.5

cat matchip-tests | grep '^[^#]' | while IFS=$'\t' read m n
do
    result=$(
	$PYTHON matchip.py $m |
	    awk '/match_subnet/ { print $2 }' |
	    sed -e 's/False/no/' -e 's/True/yes/'
    )
    if [ "$result" != "$n" ]
    then
	printf "%-30s  %s\n" "$m" "$n"
    fi
done

exit 0
