#!/bin/sh

# Test matching multiple prefix ranges simultaneously.
#
# 192.168.0.0/16 le 32
# 10.0.0.0/8 le 32
# 1.0.0.0/8 le 32
# 172.16.0.0/12 le 32

PARSEACL=../parse-acl
CONFIG1=combine-1
CONFIG2=combine-2

# Derivation using parse-acl

$PARSEACL -n -p -s '172.16.0.0/12 le 32, 192.168.0.0/16 le 32, 10.0.0.0/8 le 32, 1.0.0.0/8 le 32' $CONFIG1 2>&1 > x-result-test

trap "rm -f /tmp/x1 /tmp/x2 /tmp/x3 /tmp/x4 /tmp/x5 /tmp/x6" 0 1 2 15

# Derivation from handling each prefix range separately then merging

echo -n Test 1...

$PARSEACL -n -p -s '172.16.0.0/12 le 32' $CONFIG1 2>&1 > /tmp/x1
$PARSEACL -n -p -s '192.168.0.0/16 le 32' $CONFIG1 2>&1 > /tmp/x2
$PARSEACL -n -p -s '10.0.0.0/8 le 32' $CONFIG1 2>&1 > /tmp/x3
$PARSEACL -n -p -s '1.0.0.0/8 le 32' $CONFIG1 2>&1 > /tmp/x4

sort -t $'\t' -u -k 1,1 /tmp/x1 /tmp/x2 /tmp/x3 /tmp/x4 > y-result-test

cmp x-result-test y-result-test || exit 1
rm x-result-test y-result-test
echo OK

echo -n Test 2...

# More testing of combining but with the twice NAT statements

$PARSEACL -n -p -s '10.0.0.0/8 le 32, 172.16.0.0/12 le 32, 192.0.2.0/24 le 32, 192.168.0.0/16 le 32' $CONFIG2 2>&1 > x-result-test

$PARSEACL -n -p -s 192.168.1.10 $CONFIG2 > /tmp/x1
$PARSEACL -n -p -s 192.168.1.11 $CONFIG2 > /tmp/x2
$PARSEACL -n -p -s 10.1.1.1 $CONFIG2 > /tmp/x3
$PARSEACL -n -p -s 10.2.1.1 $CONFIG2 > /tmp/x4
$PARSEACL -n -p -s 172.16.1.2 $CONFIG2 > /tmp/x5
$PARSEACL -n -p -s 192.0.2.100 $CONFIG2 > /tmp/x6

sort -t $'\t' -u -k 1,1 /tmp/x1 /tmp/x2 /tmp/x3 /tmp/x4 /tmp/x5 /tmp/x6 > y-result-test

cmp x-result-test y-result-test || exit 1
rm x-result-test y-result-test
echo OK

exit 0
