#!/bin/bash

export LC_ALL=C

PYTHON=python
PARSEACL=../parse-acl

$PYTHON -V > /dev/null 2>&1 || { echo "$PYTHON not found "; exit 1; }

i=0
cat matchip-tests.in | grep '^[^#]' | while IFS=$'\t' read m n
do
    i=$((i+1))
    echo -n Test $i...
    result=$(
	$PYTHON $PARSEACL -t $m |
	    awk '/match_subnet/ { print $2 }' |
	    sed -e 's/False/no/' -e 's/True/yes/'
    )
    if [ "$result" != "$n" ]
    then
	printf "%-30s  %s\n" "$m" "$n"
    fi
    echo OK
done

exit 0
