#!/bin/bash

export LC_ALL=C

PARSEACL=../parse-acl

#trap "rm -f /tmp/x1 /tmp/x2 /tmp/x3 /tmp/x4" 0

echo -n Test 1...
cat <<EOF > x-result-test
object network InsideLocal
 description RFC 1918
 host 10.1.2.3
nat (inside,outside) source static InsideLocal InsideGlobal destination static OutsideLocal OutsideGlobal
EOF
$PARSEACL -s '10.0.0.0/8 le 32' twice-nat.txt > y-result-test
cmp x-result-test y-result-test || exit 1
rm x-result-test y-result-test
echo OK

echo -n Test 2...
cat <<EOF > x-result-test
EOF
$PARSEACL -d '10.0.0.0/8 le 32' twice-nat.txt > y-result-test
cmp x-result-test y-result-test || exit 1
rm x-result-test y-result-test
echo OK

echo -n Test 3...
cat <<EOF > x-result-test
object network InsideLocal
 description RFC 1918
 host 10.1.2.3
nat (inside,outside) source static InsideLocal InsideGlobal destination static OutsideLocal OutsideGlobal
EOF
$PARSEACL -p -s '10.0.0.0/8 le 32' twice-nat.txt > y-result-test
cmp x-result-test y-result-test || exit 1
rm x-result-test y-result-test
echo OK

echo -n Test 4...
cat <<EOF > x-result-test
object network OutsideLocal
 description RFC 1918
 host 172.16.1.1
EOF
$PARSEACL -s '172.16.0.0/12 le 32' twice-nat.txt > y-result-test
cmp x-result-test y-result-test || exit 1
rm x-result-test y-result-test
echo OK

echo -n Test 5...
cat <<EOF > x-result-test
nat (inside,outside) source static InsideLocal InsideGlobal destination static OutsideLocal OutsideGlobal
EOF
$PARSEACL -d '172.16.0.0/12 le 32' twice-nat.txt > y-result-test
cmp x-result-test y-result-test || exit 1
rm x-result-test y-result-test
echo OK

echo -n Test 6...
cat <<EOF > x-result-test
object network OutsideLocal
 description RFC 1918
 host 172.16.1.1
nat (inside,outside) source static InsideLocal InsideGlobal destination static OutsideLocal OutsideGlobal
EOF
$PARSEACL -p -s '172.16.0.0/12 le 32' twice-nat.txt > y-result-test
cmp x-result-test y-result-test || exit 1
rm x-result-test y-result-test
echo OK

echo -n Test 7...
cat <<EOF > x-result-test
object network InsideGlobal
 description TEST-NET-2
 host 198.51.100.1
nat (inside,outside) source static InsideLocal InsideGlobal destination static OutsideLocal OutsideGlobal
EOF
$PARSEACL -s '198.51.100.0/24 le 32' twice-nat.txt > y-result-test
cmp x-result-test y-result-test || exit 1
rm x-result-test y-result-test
echo OK

echo -n Test 8...
cat <<EOF > x-result-test
EOF
$PARSEACL -d '198.51.100.0/24 le 32' twice-nat.txt > y-result-test
cmp x-result-test y-result-test || exit 1
rm x-result-test y-result-test
echo OK

echo -n Test 9...
cat <<EOF > x-result-test
object network InsideGlobal
 description TEST-NET-2
 host 198.51.100.1
nat (inside,outside) source static InsideLocal InsideGlobal destination static OutsideLocal OutsideGlobal
EOF
$PARSEACL -p -s '198.51.100.0/24 le 32' twice-nat.txt > y-result-test
cmp x-result-test y-result-test || exit 1
rm x-result-test y-result-test
echo OK

echo -n Test 10...
cat <<EOF > x-result-test
object network OutsideGlobal
 description TEST-NET-1
 host 192.0.2.3
EOF
$PARSEACL -s '192.0.2.0/24 le 32' twice-nat.txt > y-result-test
cmp x-result-test y-result-test || exit 1
rm x-result-test y-result-test
echo OK

echo -n Test 11...
cat <<EOF > x-result-test
nat (inside,outside) source static InsideLocal InsideGlobal destination static OutsideLocal OutsideGlobal
EOF
$PARSEACL -d '192.0.2.0/24 le 32' twice-nat.txt > y-result-test
cmp x-result-test y-result-test || exit 1
rm x-result-test y-result-test
echo OK

echo -n Test 12...
cat <<EOF > x-result-test
object network OutsideGlobal
 description TEST-NET-1
 host 192.0.2.3
nat (inside,outside) source static InsideLocal InsideGlobal destination static OutsideLocal OutsideGlobal
EOF
$PARSEACL -p -s '192.0.2.0/24 le 32' twice-nat.txt > y-result-test
cmp x-result-test y-result-test || exit 1
rm x-result-test y-result-test
echo OK

echo -n Test 13...
cat <<EOF > x-result-test
nat (inside,outside) source static InsideLocal InsideGlobal destination static OutsideLocal OutsideGlobal
EOF
$PARSEACL -s '198.51.100.0/24 le 32' -d '192.0.2.0/24 le 32' twice-nat.txt > y-result-test
cmp x-result-test y-result-test || exit 1
rm x-result-test y-result-test
echo OK

echo -n Test 14...
cat <<EOF > x-result-test
nat (inside,outside) source static InsideLocal InsideGlobal destination static OutsideLocal OutsideGlobal
EOF
$PARSEACL -s '10.0.0.0/8 le 32' -d '172.16.0.0/12 le 32' twice-nat.txt > y-result-test
cmp x-result-test y-result-test || exit 1
rm x-result-test y-result-test
echo OK

exit 0
